language: node_js
matrix:
  fast_finish: true
  include:
    - node_js: "14"
      env: SCRIPT=test
    - node_js: "12"
      env: SCRIPT=test
    - node_js: "10"
      env: SCRIPT=test
    - node_js: "12"
      env: SCRIPT=test-browser
script:
  - "npm run ${SCRIPT}"
after_success:
  - 'if [ "${SCRIPT}" == "test" ]; then npm i coveralls@3 && nyc report --reporter=text-lcov | coveralls; fi'
