name: saucelab-test

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 16
        architecture:
          - x64
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: npm ci
      - name: Saucelab test
        id: test
        continue-on-error: true
        run: env SAUCE_USERNAME="${{ secrets.SAUCE_USERNAME }}" SAUCE_ACCESS_KEY="${{ secrets.SAUCE_ACCESS_KEY }}" npm run saucelab
      - name: retry
        continue-on-error: true
        id: retry1
        if: steps.test.outcome=='failure'
        run: env SAUCE_USERNAME="${{ secrets.SAUCE_USERNAME }}" SAUCE_ACCESS_KEY="${{ secrets.SAUCE_ACCESS_KEY }}" npm run saucelab
      - name: set the status              # set the workflow status if command failed
        if: always()
        run: |
          if ${{ steps.test.outcome=='success' || steps.retry1.outcome=='success' }}; then
             echo fine
          else
             exit 1
          fi
